### ISSUE TITLE
Rewrite the bot in telethon?

### ISSUE THREAD

**Issue by cofob** [LuisMayo/ace-attorney-telegram-bot#10]
This will speed up the bot, besides, the library is asynchronous.
I can do this

**Comment by LuisMayo** [comment]
Hi!
Thanks for the issue

I think the current implementation is currently multithreaded too? Like in it processes several videos at the same time? I'm not really sure.

Could you give me more info in what improvements could telethon provide?

Thanks!

**Comment by cofob** [comment]
This is an asynchronous library for Telegram, which implements MTProto (Own Telegram Protocol), which is faster and safer than HTTPs (which is used in python-telegram-bot).

**Comment by LuisMayo** [comment]
Hi!
I've read a bit and it certainly connects by MTProto instead of using the HTTP Bot API.

However:
1. The current implementation is already async in nature due to how the code works. You can try it yourself, start rendering a video and then issue an /about command. You can see that it doesn't get blocked while waiting for the video and it instead answers right away. If this isn't what you meant by "async" please try to explain it one more time
2. While it is certain that text-based protocols (like HTTP Rest bot API) carry more overheard than other kind of protocols (like MTProto), I think the cost is negligible in this case. This is a bot that literally renders and sends video files, the text-based part of the conversation may not be the one that's consuming the more time.

I don't have any special interest on using either `python-telegram-bot` nor `telethon`. I am however, struggling to understand what benefits would the switch make for such a big re-work.

Thanks again for your issue!
